<h3>Pol&iacute;tica de cookies</h3> 
<p>Las cookies son peque&ntilde;os archivos de texto que los sitios web colocan en los ordenadores de los visitantes. Por lo general son utilizados para identificar a visitantes determinados y proporcionarles una mejor experiencia. Las cookies son una parte crucial de muchas funciones del sitio web que damos por sentado. </p> 
<p>Por ejemplo, por lo general las cookies permiten a las tiendas en l&iacute;nea recordar que elementos tiene en su carrito de la compra. Tambi&eacute;n se utilizan para guardar la informaci&oacute;n de registro en un sitio web o para proporcionar estad&iacute;sticas de uso e informaci&oacute;n valiosa para los propietarios de sitios web.</p> 
<p>Si ejecuta un sitio web, es casi seguro que utiliza cookies. Su funci&oacute;n m&aacute;s probable es controlar el n&uacute;mero de visitantes y comportamientos mediante herramientas como Google Analytics. Tambi&eacute;n pueden usarse para mostrar anuncios relevantes a los visitantes. Las cookies tambi&eacute;n son partes fundamentales de su sistema de compras en l&iacute;nea.</p> 
<p>El 26 de mayo 2012 - El ICO lanz&oacute; un cambio en la pol&iacute;tica de cookies. A partir de ese momento "el consentimiento impl&iacute;cito" est&aacute; permitido, siempre y cuando quede claro d&oacute;nde se encuentra su pol&iacute;tica de privacidad/cookies.</p> 
<p>Siguiendo las condiciones de la Ley de cookies, debe a&ntilde;adir m&oacute;dulos adecuados a su sitio web que mostrar&aacute;n un mensaje de advertencia acerca de las cookies utilizadas. Podemos recomendar los siguientes:</p> 
<ul class="list">
	<li><a href="http://www.magentocommerce.com/magento-connect/catalog/product/view/id/16691/" target="_blank">Creare EU Cookie Law Banner </a></li> 
	<li><a href="http://www.magentocommerce.com/magento-connect/eu-cookie-law-compliance-implied-consent.html" target="_blank">EU Cookie Law Compliance - Consentimiento impl&iacute;cito</a></li>
</ul>